/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poo.pl2;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;
/**
 *
 * @author perez
 */
public class GUI_dialogModificarDatosPersonales extends javax.swing.JDialog {
    private Cliente cliente;
    private int indiceFijoBCB;
    private boolean forzarCierreSesion=false;
    
    public boolean isForzarCierreSesion() {
        return forzarCierreSesion;
    }

    /**
     * Creates new form GUI_dialogoModificarDatosPersonales
     */
    public GUI_dialogModificarDatosPersonales(java.awt.Frame parent, boolean modal, Cliente cliente) {
        super(parent, modal);
        this.cliente = cliente;
        initComponents();
        cargarDatos();
        prepararListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        correoLabel = new javax.swing.JLabel();
        correoField = new javax.swing.JTextField();
        cambiarContraseñaButton = new javax.swing.JButton();
        nombreLabel = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        dniLabel = new javax.swing.JLabel();
        dniField = new javax.swing.JTextField();
        telefonoLabel = new javax.swing.JLabel();
        telefonoField = new javax.swing.JTextField();
        fechaRegistroLabel = new javax.swing.JLabel();
        fechaRegistroField = new javax.swing.JTextField();
        nombreTitularTarjetaLabel = new javax.swing.JLabel();
        nombreTitularTarjetaField = new javax.swing.JTextField();
        numeroTarjetaLabel = new javax.swing.JLabel();
        numeroTarjetaField = new javax.swing.JTextField();
        mesCaducidadLabel = new javax.swing.JLabel();
        mesSpinner = new javax.swing.JSpinner();
        añoCaducidadLabel = new javax.swing.JLabel();
        añoSpinner = new javax.swing.JSpinner();
        caducidadLabel = new javax.swing.JLabel();
        modificarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boolLabel = new javax.swing.JLabel();
        boolComboBox = new javax.swing.JComboBox<>();
        volverButton = new javax.swing.JButton();
        borrarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        correoLabel.setText("Correo");

        correoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoFieldActionPerformed(evt);
            }
        });

        cambiarContraseñaButton.setText("Cambiar contraseña");
        cambiarContraseñaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContraseñaButtonActionPerformed(evt);
            }
        });

        nombreLabel.setText("Nombre");

        dniLabel.setText("DNI");

        telefonoLabel.setText("Teléfono");

        fechaRegistroLabel.setText("Fecha de Registro");

        fechaRegistroField.setEditable(false);

        nombreTitularTarjetaLabel.setText("<html><body style=\"text-align:center;\">Nombre del Titular <br> de la Tarjeta</body></html>");

        numeroTarjetaLabel.setText("Número de la Tarjeta");

        mesCaducidadLabel.setText("Mes");

        mesSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        añoCaducidadLabel.setText("Año");

        añoSpinner.setModel(new javax.swing.SpinnerNumberModel(2024, 2024, null, 1));

        caducidadLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        caducidadLabel.setText("Caducidad");

        modificarButton.setText("Modificar Datos");
        modificarButton.setEnabled(false);
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar Cambios");
        cancelarButton.setEnabled(false);
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("MODIFICAR DATOS PERSONALES");

        boolLabel.setText("¿Es Súper Propietario?");

        boolComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        boolComboBox.setEditable(false);
        boolComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boolComboBoxActionPerformed(evt);
            }
        });

        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        borrarButton.setBackground(new java.awt.Color(255, 0, 0));
        borrarButton.setForeground(new java.awt.Color(255, 255, 255));
        borrarButton.setText("Borrar Cuenta");
        borrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nombreTitularTarjetaField)
                                        .addComponent(nombreTitularTarjetaLabel)
                                        .addComponent(nombreField)
                                        .addComponent(nombreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(correoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(correoField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(boolComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(boolLabel, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(telefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(numeroTarjetaField, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(numeroTarjetaLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(mesCaducidadLabel)
                                                        .addGap(27, 27, 27)
                                                        .addComponent(añoCaducidadLabel))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(mesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(añoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(caducidadLabel)))
                                            .addComponent(fechaRegistroField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fechaRegistroLabel))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dniLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(telefonoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modificarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cambiarContraseñaButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1)
                        .addGap(0, 74, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(volverButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(borrarButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(correoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreLabel)
                            .addComponent(dniLabel)
                            .addComponent(telefonoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fechaRegistroLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaRegistroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boolLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boolComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addComponent(nombreTitularTarjetaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(caducidadLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeroTarjetaLabel)
                            .addComponent(mesCaducidadLabel)
                            .addComponent(añoCaducidadLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTitularTarjetaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroTarjetaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarButton)
                    .addComponent(cancelarButton)
                    .addComponent(cambiarContraseñaButton))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverButton)
                    .addComponent(borrarButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void correoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoFieldActionPerformed
        
    }//GEN-LAST:event_correoFieldActionPerformed

    private void cambiarContraseñaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContraseñaButtonActionPerformed
        String nuevaContraseña = JOptionPane.showInputDialog(this, "Introduce la nueva contraseña", "Cambiar contraseña", JOptionPane.QUESTION_MESSAGE);
        String nuevaContraseña2 = JOptionPane.showInputDialog(this, "Introduce la nueva contraseña de nuevo", "Cambiar contraseña", JOptionPane.QUESTION_MESSAGE);
        try{
            Usuario.cambiarContraseña(this.cliente.getCorreo(), nuevaContraseña, nuevaContraseña2);
            JOptionPane.showMessageDialog(this, "Contraseña cambiada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cambiarContraseñaButtonActionPerformed

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
        //Si no se ha hecho ningún cambio, return
        //if (this.correoField.getText().equals(this.cliente.getCorreo()) && this.nombreField.getText().equals(this.cliente.getNombre()) && this.dniField.getText().equals(this.cliente.getDni()) && this.telefonoField.getText().equals(this.cliente.getTelefono()) &&( this.cliente instanceof Anfitrion || (this.cliente instanceof Particular && (this.numeroTarjetaField.getText().equals(Long.toString(((Particular)this.cliente).getTarjeta().getNumero())) && this.nombreTitularTarjetaField.getText().equals(((Particular)this.cliente).getTarjeta().getNombreTitular()) && (int)this.mesSpinner.getValue()==((Particular)this.cliente).getTarjeta().getFechaCaducidad().getMonthValue() && (int)this.añoSpinner.getValue()==((Particular)this.cliente).getTarjeta().getFechaCaducidad().getYear())))){
            //System.out.println("No se ha hecho ningún cambio");
            //return;
        //}
        try{
            System.out.println("Se va a editar a "+this.cliente.toString());
            switch(this.cliente.getClass().getSimpleName()){
                case "Particular":
                Usuario.editarUsuario(this.cliente.getCorreo(), this.correoField.getText(), this.dniField.getText(), this.nombreField.getText(), this.telefonoField.getText(), this.boolComboBox.getSelectedIndex()==0, new Tarjeta(LocalDate.of((int)this.añoSpinner.getValue(), (int)this.mesSpinner.getValue(), 1), this.nombreTitularTarjetaField.getText(), Long.parseLong(this.numeroTarjetaField.getText())));
                break;
                case "Anfitrion":
                Usuario.editarUsuario(this.cliente.getCorreo(), this.correoField.getText(), this.dniField.getText(), this.nombreField.getText(), this.telefonoField.getText());
                break;
                case "Administrador":
                Usuario.editarUsuario(this.cliente.getCorreo(), this.correoField.getText());
                break;
            }
            JOptionPane.showMessageDialog(this, "Cambios realizados correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            modificarButton.setEnabled(false);
            cancelarButton.setEnabled(false);
        }
        catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modificarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        cargarDatos();
        modificarButton.setEnabled(false);
        cancelarButton.setEnabled(false);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_volverButtonActionPerformed

    private void boolComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boolComboBoxActionPerformed
        if (this.cliente instanceof Particular && !((Particular)this.cliente).isVip() && boolComboBox.getSelectedIndex()==0){
            String codigoVip=JOptionPane.showInputDialog(this, "Introduce el código VIP", "Código VIP", JOptionPane.QUESTION_MESSAGE);
            if (codigoVip!=null && codigoVip.equals(Usuario.getClaveVip())){
                JOptionPane.showMessageDialog(this, "Código VIP correcto", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                indiceFijoBCB=0;
                cambioRealizado();
            }
            else{
                JOptionPane.showMessageDialog(this, "Código VIP incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
                boolComboBox.setSelectedIndex(indiceFijoBCB);
            }
        }
        else
            boolComboBox.setSelectedIndex(indiceFijoBCB);
    }//GEN-LAST:event_boolComboBoxActionPerformed

    private void borrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonActionPerformed
        boolean confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres borrar tu cuenta?\n", "Borrar cuenta", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE)==JOptionPane.YES_OPTION;
        if (confirmacion){
            try{
                Usuario.borrarUsuario(this.cliente.getCorreo());
                JOptionPane.showMessageDialog(this, "Cuenta borrada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.forzarCierreSesion=true;
                this.dispose();
            }
            catch (IllegalArgumentException e){
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_borrarButtonActionPerformed
    private void cargarDatos(){
        indiceFijoBCB=cliente instanceof Particular? ((Particular)cliente).isVip()?0:1 : ((Anfitrion)cliente).isSuperAnfitrion()?0:1;
        Cliente clienteSeleccionado = this.cliente;
        this.correoField.setText(clienteSeleccionado.getCorreo());
        this.nombreField.setVisible(true);
        this.nombreLabel.setVisible(true);
        this.dniField.setVisible(true);
        this.dniLabel.setVisible(true);
        this.telefonoField.setVisible(true);
        this.telefonoLabel.setVisible(true);
        this.boolLabel.setVisible(true);
        this.boolComboBox.setVisible(true);
        this.nombreField.setText(clienteSeleccionado.getNombre());
        this.dniField.setText(clienteSeleccionado.getDni());
        this.telefonoField.setText(clienteSeleccionado.getTelefono());
        if (clienteSeleccionado instanceof Anfitrion){
            Anfitrion anfitrionSeleccionado = (Anfitrion) clienteSeleccionado;
            this.boolLabel.setText("¿Es Súper Anfitrión?");
            this.boolComboBox.setSelectedIndex(anfitrionSeleccionado.isSuperAnfitrion()?0:1);
            this.fechaRegistroLabel.setVisible(true);
            this.fechaRegistroField.setVisible(true);
            this.fechaRegistroField.setText(anfitrionSeleccionado.getFechaRegistro().toString());
            this.numeroTarjetaLabel.setVisible(false);
            this.numeroTarjetaField.setVisible(false);
            this.nombreTitularTarjetaLabel.setVisible(false);
            this.nombreTitularTarjetaField.setVisible(false);
            this.caducidadLabel.setVisible(false);
            this.mesCaducidadLabel.setVisible(false);
            this.mesSpinner.setVisible(false);
            this.añoCaducidadLabel.setVisible(false);
            this.añoSpinner.setVisible(false);
        }else{
            Particular particularSeleccionado = (Particular) clienteSeleccionado;
            this.boolLabel.setText("¿Es VIP?");
            this.boolComboBox.setSelectedIndex(particularSeleccionado.isVip()?0:1);
            this.fechaRegistroLabel.setVisible(false);
            this.fechaRegistroField.setVisible(false);
            this.numeroTarjetaLabel.setVisible(true);
            this.numeroTarjetaField.setVisible(true);
            this.nombreTitularTarjetaLabel.setVisible(true);
            this.nombreTitularTarjetaField.setVisible(true);
            this.caducidadLabel.setVisible(true);
            this.mesCaducidadLabel.setVisible(true);
            this.mesSpinner.setVisible(true);
            this.añoCaducidadLabel.setVisible(true);
            this.añoSpinner.setVisible(true);
            this.numeroTarjetaField.setText(Long.toString(particularSeleccionado.getTarjeta().getNumero()));
            this.nombreTitularTarjetaField.setText(particularSeleccionado.getTarjeta().getNombreTitular());
            this.mesSpinner.setValue(particularSeleccionado.getTarjeta().getFechaCaducidad().getMonthValue());
            this.añoSpinner.setValue(particularSeleccionado.getTarjeta().getFechaCaducidad().getYear());
        }
        
    }
    private void cambioRealizado(){
        if (this.nombreField.getText().equals(this.cliente.getNombre()) && this.correoField.getText().equals(this.cliente.getCorreo()) && this.dniField.getText().equals(this.cliente.getDni()) && this.telefonoField.getText().equals(this.cliente.getTelefono()) &&( this.cliente instanceof Anfitrion || (this.cliente instanceof Particular && (this.numeroTarjetaField.getText().equals(Long.toString(((Particular)this.cliente).getTarjeta().getNumero())) && this.nombreTitularTarjetaField.getText().equals(((Particular)this.cliente).getTarjeta().getNombreTitular()) && (int)this.mesSpinner.getValue()==((Particular)this.cliente).getTarjeta().getFechaCaducidad().getMonthValue() && (int)this.añoSpinner.getValue()==((Particular)this.cliente).getTarjeta().getFechaCaducidad().getYear()) && (this.boolComboBox.getSelectedIndex()==0)==((Particular)this.cliente).isVip()))){
            modificarButton.setEnabled(false);
            cancelarButton.setEnabled(false);
            return;
        }
        modificarButton.setEnabled(true);
        cancelarButton.setEnabled(true);
    }
    private void prepararListeners(){
        this.correoField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                cambioRealizado();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                cambioRealizado();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                cambioRealizado();
            }
        });
        this.nombreField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                cambioRealizado();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                cambioRealizado();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                cambioRealizado();
            }
        });
        this.dniField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                cambioRealizado();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                cambioRealizado();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                cambioRealizado();
            }
        });
        this.telefonoField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                cambioRealizado();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                cambioRealizado();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                cambioRealizado();
            }
        });
        this.nombreTitularTarjetaField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                cambioRealizado();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                cambioRealizado();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                cambioRealizado();
            }
        });
        this.numeroTarjetaField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                cambioRealizado();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                cambioRealizado();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                cambioRealizado();
            }
        });
        this.mesSpinner.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                cambioRealizado();
            }
        });
        this.añoSpinner.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                cambioRealizado();
            }
        });

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_dialogModificarDatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_dialogModificarDatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_dialogModificarDatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_dialogModificarDatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI_dialogModificarDatosPersonales dialog = new GUI_dialogModificarDatosPersonales(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel añoCaducidadLabel;
    private javax.swing.JSpinner añoSpinner;
    private javax.swing.JComboBox<String> boolComboBox;
    private javax.swing.JLabel boolLabel;
    private javax.swing.JButton borrarButton;
    private javax.swing.JLabel caducidadLabel;
    private javax.swing.JButton cambiarContraseñaButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField correoField;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JTextField dniField;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField fechaRegistroField;
    private javax.swing.JLabel fechaRegistroLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mesCaducidadLabel;
    private javax.swing.JSpinner mesSpinner;
    private javax.swing.JButton modificarButton;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTitularTarjetaField;
    private javax.swing.JLabel nombreTitularTarjetaLabel;
    private javax.swing.JTextField numeroTarjetaField;
    private javax.swing.JLabel numeroTarjetaLabel;
    private javax.swing.JTextField telefonoField;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
