/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poo.pl2;

import java.awt.Component;
import java.awt.Container;
import java.util.ArrayList;
/**
 *
 * @author tizia
 */
public class GUI_dialogReservas extends javax.swing.JDialog {

    ArrayList<Reserva> reservas = new ArrayList<>();
    Particular usuario;
    /**
     * Creates new form GUI_dialogReseñas
     */
    public GUI_dialogReservas(java.awt.Frame parent, boolean modal, Particular usuario) {
        super(parent, modal);
        initComponents();
        this.usuario = usuario;
        for (int i=0; i<Reserva.getReservas().size(); i++)
            if (Reserva.getReservas().get(i).getParticular().equals(usuario))
                reservas.add(Reserva.getReservas().get(i));
        String[] listaFinal = new String[reservas.size()];
        for (int i=0; i<reservas.size(); i++)
            listaFinal[i] = reservas.get(i).getInmueble().getTitulo()+": "+reservas.get(i).getFechaEntrada().toString()+" - "+reservas.get(i).getFechaSalida().toString();
        this.reservasList.setListData(listaFinal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calificacionButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservasList = new javax.swing.JList<>();
        reservaPanel = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fechaEntradaField = new javax.swing.JTextField();
        fechaSalidaField = new javax.swing.JTextField();
        importeField = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tipoInmuebleField = new javax.swing.JTextField();
        direccionField = new javax.swing.JTextField();
        tituloField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        precioField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        calificacionField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        serviciosArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        datosArea = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fotoLabel = new javax.swing.JLabel();
        verReseñasButton = new javax.swing.JButton();
        dueñoLabel = new javax.swing.JLabel();
        dueñoField = new javax.swing.JTextField();
        reseñaFrame = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        calificacion1RadioButton = new javax.swing.JRadioButton();
        calificacion2RadioButton = new javax.swing.JRadioButton();
        calificacion3RadioButton = new javax.swing.JRadioButton();
        calificacion4RadioButton = new javax.swing.JRadioButton();
        calificacion5RadioButton = new javax.swing.JRadioButton();
        aceptarButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        comentarioArea = new javax.swing.JTextArea();
        noPuedesLabel = new javax.swing.JLabel();
        volverButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Mis reservas");

        reservasList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        reservasList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                reservasListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(reservasList);

        reservaPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                reservaPanelStateChanged(evt);
            }
        });

        jInternalFrame1.setVisible(true);

        jLabel3.setText("Fecha de entrada");

        jLabel4.setText("Fecha de salida");

        jLabel5.setText("Importe");

        fechaEntradaField.setEditable(false);

        fechaSalidaField.setEditable(false);

        importeField.setEditable(false);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(importeField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaSalidaField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(fechaEntradaField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(fechaEntradaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaSalidaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        reservaPanel.addTab("Datos", jInternalFrame1);

        jInternalFrame3.setVisible(true);

        jLabel8.setText("Título");

        jLabel11.setText("Dirección");

        jLabel9.setText("Tipo");

        jLabel14.setText("Servicios");

        tipoInmuebleField.setEditable(false);

        direccionField.setEditable(false);

        tituloField.setEditable(false);

        jLabel13.setText("Precio por noche");

        precioField.setEditable(false);

        jLabel15.setText("Calificación");

        calificacionField.setEditable(false);

        serviciosArea.setEditable(false);
        serviciosArea.setColumns(20);
        serviciosArea.setRows(5);
        jScrollPane2.setViewportView(serviciosArea);

        datosArea.setEditable(false);
        datosArea.setColumns(20);
        datosArea.setRows(5);
        jScrollPane3.setViewportView(datosArea);

        jLabel12.setText("Datos");

        jLabel16.setText("Foto");

        fotoLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        verReseñasButton.setText("Ver reseñas del inmueble");
        verReseñasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verReseñasButtonActionPerformed(evt);
            }
        });

        dueñoLabel.setText("Dueño");
        dueñoLabel.setToolTipText("<html>\n<body style=\"text-align:center\">\n<p>Un dueño es superanfitrión si la media<br/>de las calificaciones de sus inmuebles<br/> es superior a 4\n</body>\n</html>");

        dueñoField.setEditable(false);
        dueñoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verReseñasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(precioField)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tituloField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(direccionField)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(calificacionField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tipoInmuebleField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addComponent(dueñoLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(dueñoField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verReseñasButton)))
                .addContainerGap())
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoInmuebleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calificacionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(5, 5, 5)
                .addComponent(dueñoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dueñoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verReseñasButton))
                .addGap(8, 8, 8)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jInternalFrame3);

        reservaPanel.addTab("Inmueble", jScrollPane5);

        reseñaFrame.setVisible(true);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Calificación");

        calificacionButtonGroup.add(calificacion1RadioButton);
        calificacion1RadioButton.setText("1");

        calificacionButtonGroup.add(calificacion2RadioButton);
        calificacion2RadioButton.setText("2");

        calificacionButtonGroup.add(calificacion3RadioButton);
        calificacion3RadioButton.setText("3");

        calificacionButtonGroup.add(calificacion4RadioButton);
        calificacion4RadioButton.setText("4");

        calificacionButtonGroup.add(calificacion5RadioButton);
        calificacion5RadioButton.setText("5");

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Comentario (opcional)");

        comentarioArea.setColumns(20);
        comentarioArea.setRows(5);
        jScrollPane4.setViewportView(comentarioArea);

        noPuedesLabel.setForeground(new java.awt.Color(255, 51, 51));
        noPuedesLabel.setText("<html><body style=\"text-align:center;\"><p>No puedes reseñar el inmueble hasta<br/>completar tu estancia</body></html>");

        javax.swing.GroupLayout reseñaFrameLayout = new javax.swing.GroupLayout(reseñaFrame.getContentPane());
        reseñaFrame.getContentPane().setLayout(reseñaFrameLayout);
        reseñaFrameLayout.setHorizontalGroup(
            reseñaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reseñaFrameLayout.createSequentialGroup()
                .addGroup(reseñaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reseñaFrameLayout.createSequentialGroup()
                        .addGroup(reseñaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reseñaFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6))
                            .addGroup(reseñaFrameLayout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(aceptarButton))
                            .addGroup(reseñaFrameLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(reseñaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(reseñaFrameLayout.createSequentialGroup()
                                        .addComponent(calificacion1RadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(calificacion2RadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(calificacion3RadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(calificacion4RadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(calificacion5RadioButton))))
                            .addGroup(reseñaFrameLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(noPuedesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(reseñaFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );
        reseñaFrameLayout.setVerticalGroup(
            reseñaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reseñaFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noPuedesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reseñaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calificacion1RadioButton)
                    .addComponent(calificacion2RadioButton)
                    .addComponent(calificacion3RadioButton)
                    .addComponent(calificacion4RadioButton)
                    .addComponent(calificacion5RadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aceptarButton)
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        reservaPanel.addTab("Reseñar", reseñaFrame);

        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(reservaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(volverButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reservaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volverButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservasListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_reservasListValueChanged
        this.fechaEntradaField.setText(reservas.get(reservasList.getSelectedIndex()).getFechaEntrada().toString());
        this.fechaSalidaField.setText(reservas.get(reservasList.getSelectedIndex()).getFechaSalida().toString());
        this.importeField.setText(String.valueOf(reservas.get(reservasList.getSelectedIndex()).getImporte()));
        this.tituloField.setText(reservas.get(reservasList.getSelectedIndex()).getInmueble().getTitulo());
        this.direccionField.setText(reservas.get(reservasList.getSelectedIndex()).getInmueble().getDireccion().toString());
        this.tipoInmuebleField.setText(reservas.get(reservasList.getSelectedIndex()).getInmueble().getTipo()==Inmueble.tipoPropiedad.CASA?"Casa":"Apartamento");
        this.precioField.setText(String.valueOf(reservas.get(reservasList.getSelectedIndex()).getInmueble().getPrecioPorNoche()));
        this.calificacionField.setText(String.valueOf(reservas.get(reservasList.getSelectedIndex()).getInmueble().getCalificacion()));
        Inmueble i = reservas.get(reservasList.getSelectedIndex()).getInmueble();
        this.datosArea.setText("Baños: "+i.getBaños()+"\nHuéspedes: "+i.getHuespedesMaximos()+"\nHabitaciones: "+i.getHabitaciones()+"Camas: "+i.getCamas());
        this.serviciosArea.setText(i.getServicios());
        this.fotoLabel.setIcon(i.getFotografia());
        this.dueñoLabel.setText(reservas.get(reservasList.getSelectedIndex()).getInmueble().getDueño().isSuperAnfitrion()?"Dueño (¡Es superanfitrión!)":"Dueño");
        this.dueñoField.setText(reservas.get(reservasList.getSelectedIndex()).getInmueble().getDueño().getNombre()+ "("+reservas.get(reservasList.getSelectedIndex()).getInmueble().getDueño().getCorreo()+")");
    }//GEN-LAST:event_reservasListValueChanged

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_volverButtonActionPerformed

    private void reservaPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_reservaPanelStateChanged
        if(reservaPanel.getSelectedIndex()==2)
            if (reservas.get(reservasList.getSelectedIndex()).getFechaSalida().isAfter(java.time.LocalDate.now()) || reservas.get(reservasList.getSelectedIndex()).isYaReseñado()){
                noPuedesLabel.setVisible(true);
                noPuedesLabel.setText(reservas.get(reservasList.getSelectedIndex()).isYaReseñado()?"Ya has reseñado este inmueble":"<html><body style=\"text-align:center;\"><p>No puedes reseñar el inmueble hasta<br/>completar tu estancia</body></html>");
                setEnableRecursivo(reseñaFrame, false);
                noPuedesLabel.setEnabled(true);
            }else{
                noPuedesLabel.setVisible(false);
                setEnableRecursivo(reseñaFrame, true);
            }
    }//GEN-LAST:event_reservaPanelStateChanged

    private void verReseñasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verReseñasButtonActionPerformed
        GUI_dialogVerReseñas dialogoReservas = new GUI_dialogVerReseñas(this, true, reservas.get(reservasList.getSelectedIndex()).getInmueble());
        dialogoReservas.setVisible(true);
    }//GEN-LAST:event_verReseñasButtonActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        reservas.get(reservasList.getSelectedIndex()).getInmueble().añadirReseña(new Reseña(reservas.get(reservasList.getSelectedIndex()), this.calificacionButtonGroup.getSelection().equals(this.calificacion1RadioButton.getModel())?1:this.calificacionButtonGroup.getSelection().equals(this.calificacion2RadioButton.getModel())?2:this.calificacionButtonGroup.getSelection().equals(this.calificacion3RadioButton.getModel())?3:this.calificacionButtonGroup.getSelection().equals(this.calificacion4RadioButton.getModel())?4:5, this.comentarioArea.getText()));
    }//GEN-LAST:event_aceptarButtonActionPerformed
    private void setEnableRecursivo(Component container, boolean enable) {
        container.setEnabled(enable);
    
        try {
            Component[] components = ((Container) container).getComponents();
            for (Component component : components) {
                setEnableRecursivo(component, enable);
            }
        } catch (ClassCastException e) {
            // No es un contenedor, no hay nada que hacer
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_dialogReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_dialogReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_dialogReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_dialogReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI_dialogReservas dialog = new GUI_dialogReservas(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JRadioButton calificacion1RadioButton;
    private javax.swing.JRadioButton calificacion2RadioButton;
    private javax.swing.JRadioButton calificacion3RadioButton;
    private javax.swing.JRadioButton calificacion4RadioButton;
    private javax.swing.JRadioButton calificacion5RadioButton;
    private javax.swing.ButtonGroup calificacionButtonGroup;
    private javax.swing.JTextField calificacionField;
    private javax.swing.JTextArea comentarioArea;
    private javax.swing.JTextArea datosArea;
    private javax.swing.JTextField direccionField;
    private javax.swing.JTextField dueñoField;
    private javax.swing.JLabel dueñoLabel;
    private javax.swing.JTextField fechaEntradaField;
    private javax.swing.JTextField fechaSalidaField;
    private javax.swing.JLabel fotoLabel;
    private javax.swing.JTextField importeField;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel noPuedesLabel;
    private javax.swing.JTextField precioField;
    private javax.swing.JTabbedPane reservaPanel;
    private javax.swing.JList<String> reservasList;
    private javax.swing.JInternalFrame reseñaFrame;
    private javax.swing.JTextArea serviciosArea;
    private javax.swing.JTextField tipoInmuebleField;
    private javax.swing.JTextField tituloField;
    private javax.swing.JButton verReseñasButton;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
