/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.pl2;

import java.time.LocalDate;
import java.util.ArrayList;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import java.awt.Color;
import java.awt.Component;
/**
 *
 * @author tizia
 */
public class GUI_mainAdmin extends javax.swing.JFrame {
    private Administrador usuario=null;
    private ArrayList<Integer> posicionesSeparador=new ArrayList<Integer>();
    private int seleccionAnterior=-1;
    private int indiceFijoBCB=0;
    /**
     * Creates new form mainAdmin
     */
    public GUI_mainAdmin(Administrador usuario) {
        this.usuario=usuario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        listaComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        elementosList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        datosPanel = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        correoLabel = new javax.swing.JLabel();
        correoField = new javax.swing.JTextField();
        tipoUsuarioLabel = new javax.swing.JLabel();
        tipoUsuarioField = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        dniField = new javax.swing.JTextField();
        telefonoLabel = new javax.swing.JLabel();
        telefonoField = new javax.swing.JTextField();
        boolLabel = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        cambiarContraseñaButton = new javax.swing.JButton();
        boolComboBox = new javax.swing.JComboBox<>();
        fechaRegistroLabel = new javax.swing.JLabel();
        nombreTitularTarjetaLabel = new javax.swing.JLabel();
        nombreTitularTarjetaField = new javax.swing.JTextField();
        fechaRegistroField = new javax.swing.JTextField();
        numeroTarjetaLabel = new javax.swing.JLabel();
        numeroTarjetaField = new javax.swing.JTextField();
        caducidadLabel = new javax.swing.JLabel();
        mesCaducidadLabel = new javax.swing.JLabel();
        mesSpinner = new javax.swing.JSpinner();
        añoCaducidadLabel = new javax.swing.JLabel();
        añoSpinner = new javax.swing.JSpinner();
        extenderButton = new javax.swing.JButton();
        modificarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        cerrarSesionButton = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        tituloField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        direccionField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tipoInmuebleField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        precioField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        calificacionField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        serviciosArea = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        datosArea = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        fotoArea = new javax.swing.JTextArea();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jLabel17 = new javax.swing.JLabel();
        entradaField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        salidaField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        fechaReservaField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        importeField = new javax.swing.JTextField();
        tituloLabel = new javax.swing.JLabel();
        labelDebug = new javax.swing.JLabel();
        añadirAdminButton = new javax.swing.JButton();
        borrarUsuarioButton = new javax.swing.JButton();

        jLabel21.setText("jLabel21");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaBnB");

        listaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuarios", "Inmuebles", "Reservas" }));

        posicionesSeparador=new ArrayList<Integer>();
        ArrayList<String> correosLista=new ArrayList<String>();
        String clasePrevia="";
        int i=0;
        for (Usuario u:ListManager.usuarios){
            if (!u.getClass().getSimpleName().equals(clasePrevia)){
                correosLista.add(u.getClass().getSimpleName()+"es:");
                posicionesSeparador.add(i);
                i++;
            }
            correosLista.add(u.getCorreo());
            clasePrevia=u.getClass().getSimpleName();
            i++;
        }
        elementosList.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                // Cambia el color de fondo de los elementos en los índices impares
                if (posicionesSeparador.contains(index)) {
                    c.setBackground(new Color(225,225,225));
                } else {
                    c.setBackground(Color.WHITE);
                }

                return c;
            }
        });
        elementosList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings=correosLista.toArray(new String[correosLista.size()]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        elementosList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        elementosList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                elementosListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(elementosList);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Lista de tipo:");

        jInternalFrame1.setTitle("Datos de usuario");
        jInternalFrame1.setVisible(true);

        correoLabel.setText("Correo");

        correoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoFieldActionPerformed(evt);
            }
        });

        tipoUsuarioLabel.setText("Tipo de Usuario");

        tipoUsuarioField.setEditable(false);

        nombreLabel.setText("Nombre");

        dniLabel.setText("DNI");

        telefonoLabel.setText("Teléfono");

        boolLabel.setText("¿Es Súper Propietario?");

        cambiarContraseñaButton.setText("Cambiar contraseña");
        cambiarContraseñaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContraseñaButtonActionPerformed(evt);
            }
        });

        boolComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        boolComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boolComboBoxActionPerformed(evt);
            }
        });

        fechaRegistroLabel.setText("Fecha de Registro");

        nombreTitularTarjetaLabel.setText("<html><body style=\"text-align:center;\">Nombre del Titular <br> de la Tarjeta</body></html>");

        fechaRegistroField.setEditable(false);

        numeroTarjetaLabel.setText("Número de la Tarjeta");

        caducidadLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        caducidadLabel.setText("Caducidad");

        mesCaducidadLabel.setText("Mes");

        mesSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        añoCaducidadLabel.setText("Año");

        añoSpinner.setModel(new javax.swing.SpinnerNumberModel(2024, 2024, null, 1));

        extenderButton.setText("Ver/Editar Reservas");
        extenderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extenderButtonActionPerformed(evt);
            }
        });

        modificarButton.setText("Modificar Usuario");
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar Cambios");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        cerrarSesionButton.setText("Cerrar Sesión");
        cerrarSesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nombreTitularTarjetaField)
                    .addComponent(nombreTitularTarjetaLabel)
                    .addComponent(boolComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boolLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreField)
                    .addComponent(nombreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(correoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(correoField, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(dniLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefonoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fechaRegistroField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dniField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefonoField))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoUsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(tipoUsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cambiarContraseñaButton))
                                    .addComponent(fechaRegistroLabel)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(numeroTarjetaField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(numeroTarjetaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addComponent(mesCaducidadLabel)
                                                .addGap(27, 27, 27)
                                                .addComponent(añoCaducidadLabel))
                                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addComponent(mesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(añoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(extenderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 48, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(caducidadLabel)
                        .addGap(51, 51, 51))))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(modificarButton)
                .addGap(65, 65, 65)
                .addComponent(cancelarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarSesionButton)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(correoLabel)
                            .addComponent(tipoUsuarioLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoUsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cambiarContraseñaButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreLabel)
                            .addComponent(dniLabel)
                            .addComponent(telefonoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boolLabel)
                            .addComponent(fechaRegistroLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boolComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaRegistroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreTitularTarjetaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(caducidadLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeroTarjetaLabel)
                            .addComponent(mesCaducidadLabel)
                            .addComponent(añoCaducidadLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTitularTarjetaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroTarjetaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(extenderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarButton)
                    .addComponent(cancelarButton))
                .addGap(10, 10, 10)
                .addComponent(cerrarSesionButton)
                .addContainerGap())
        );

        datosPanel.addTab("Usuario", jInternalFrame1);

        jInternalFrame2.setTitle("Datos de inmueble");
        jInternalFrame2.setVisible(true);

        jLabel8.setText("Título");

        jLabel11.setText("Dirección");

        jLabel9.setText("Tipo");

        jLabel13.setText("Precio por noche");

        jLabel15.setText("Calificación");

        jLabel14.setText("Servicios");

        serviciosArea.setColumns(20);
        serviciosArea.setRows(5);
        jScrollPane2.setViewportView(serviciosArea);

        jLabel12.setText("Datos");

        datosArea.setColumns(20);
        datosArea.setRows(5);
        jScrollPane3.setViewportView(datosArea);

        jLabel16.setText("Foto");

        fotoArea.setColumns(20);
        fotoArea.setRows(5);
        jScrollPane4.setViewportView(fotoArea);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(precioField)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tituloField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(direccionField)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(calificacionField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tipoInmuebleField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jScrollPane4))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoInmuebleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calificacionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        datosPanel.addTab("Inmueble", jInternalFrame2);

        jInternalFrame3.setTitle("Datos de reserva");
        jInternalFrame3.setVisible(true);

        jLabel17.setText("Fecha de entrada");

        jLabel18.setText("Fecha de salida");

        jLabel19.setText("Fecha de reserva");

        jLabel20.setText("Importe");

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(importeField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(entradaField, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(salidaField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(fechaReservaField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salidaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaReservaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        datosPanel.addTab("Reserva", jInternalFrame3);

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Panel de Administración");

        labelDebug.setText(this.usuario.toString());

        añadirAdminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo/pl2/Recursos/añadirAdmin.png"))); // NOI18N
        añadirAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirAdminButtonActionPerformed(evt);
            }
        });

        borrarUsuarioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo/pl2/Recursos/borrarUsuario.png"))); // NOI18N
        borrarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarUsuarioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(labelDebug)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(añadirAdminButton)
                            .addComponent(borrarUsuarioButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 35, Short.MAX_VALUE)
                        .addComponent(datosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(listaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(añadirAdminButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(borrarUsuarioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDebug))
        );

        datosPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void refrescarLista(){
        posicionesSeparador=new ArrayList<Integer>();
                ArrayList<String> correosLista=new ArrayList<String>();
                String clasePrevia="";
                int i=0;
                for (Usuario u:ListManager.usuarios){
                    if (!u.getClass().getSimpleName().equals(clasePrevia)){
                        correosLista.add(u.getClass().getSimpleName()+"es:");
                        posicionesSeparador.add(i);
                        i++;
                    }
                    correosLista.add(u.getCorreo());
                    clasePrevia=u.getClass().getSimpleName();
                    i++;
                }
                elementosList.setModel(new javax.swing.AbstractListModel<String>() {
                    String[] strings=correosLista.toArray(new String[correosLista.size()]);
                    public int getSize() { return strings.length; }
                    public String getElementAt(int i) { return strings[i]; }
                });
    }
    private void correoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoFieldActionPerformed

    private void cambiarContraseñaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContraseñaButtonActionPerformed
        String nuevaContraseña = JOptionPane.showInputDialog(this, "Introduce la nueva contraseña", "Cambiar contraseña", JOptionPane.QUESTION_MESSAGE);
        String nuevaContraseña2 = JOptionPane.showInputDialog(this, "Introduce la nueva contraseña de nuevo", "Cambiar contraseña", JOptionPane.QUESTION_MESSAGE);
        try{
            LoginManager loginManager = new LoginManager();
            loginManager.cambiarContraseña(ListManager.usuarios.get(this.elementosList.getSelectedIndex()-(int)posicionesSeparador.stream().filter(i->i<elementosList.getSelectedIndex()).count()).getCorreo(), nuevaContraseña, nuevaContraseña2);
            JOptionPane.showMessageDialog(this, "Contraseña cambiada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cambiarContraseñaButtonActionPerformed

    private void extenderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extenderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extenderButtonActionPerformed

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
        if (elementosList.getSelectedIndex()==-1 || posicionesSeparador.contains(elementosList.getSelectedIndex())){
            JOptionPane.showMessageDialog(this, "Selecciona un usuario para modificar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            LoginManager loginManager = new LoginManager();
            System.out.println("Se va a editar a "+ListManager.usuarios.get(elementosList.getSelectedIndex()-(int)posicionesSeparador.stream().filter(i->i<elementosList.getSelectedIndex()).count()).toString());
            switch(ListManager.usuarios.get(elementosList.getSelectedIndex()-(int)posicionesSeparador.stream().filter(i->i<elementosList.getSelectedIndex()).count()).getClass().getSimpleName()){
                case "Particular":
                    loginManager.editarUsuario(ListManager.usuarios.get(elementosList.getSelectedIndex()-(int)posicionesSeparador.stream().filter(i -> i<elementosList.getSelectedIndex()).count()).getCorreo(), this.correoField.getText(), this.dniField.getText(), this.nombreField.getText(), this.telefonoField.getText(), this.boolComboBox.getSelectedIndex()==0, new Tarjeta(LocalDate.of((int)this.añoSpinner.getValue(), (int)this.mesSpinner.getValue(), 1), this.nombreTitularTarjetaField.getText(), Long.parseLong(this.numeroTarjetaField.getText())));
                    break;
                case "Anfitrion":
                    loginManager.editarUsuario(ListManager.usuarios.get(elementosList.getSelectedIndex()-(int)posicionesSeparador.stream().filter(i->i<elementosList.getSelectedIndex()).count()).getCorreo(), this.correoField.getText(), this.dniField.getText(), this.nombreField.getText(), this.telefonoField.getText());
                    break;
                case "Administrador":
                    loginManager.editarUsuario(ListManager.usuarios.get(elementosList.getSelectedIndex()-(int)posicionesSeparador.stream().filter(i->i<elementosList.getSelectedIndex()).count()).getCorreo(), this.correoField.getText());
                    break;
            }
            JOptionPane.showMessageDialog(this, "Usuario modificado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            refrescarLista();
        }
        catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modificarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        elementosListValueChanged(null);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void elementosListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_elementosListValueChanged
        if(listaComboBox.getSelectedIndex()==0){
            if(elementosList.getSelectedIndex()!=-1 && !posicionesSeparador.contains(elementosList.getSelectedIndex())){
                Usuario usuarioSeleccionado = ListManager.usuarios.get(elementosList.getSelectedIndex()-(int)posicionesSeparador.stream().filter(i->i<elementosList.getSelectedIndex()).count());
                System.out.println(posicionesSeparador.toString());
                System.out.println(Integer.toString(elementosList.getSelectedIndex())+"-"+Integer.toString((int)posicionesSeparador.stream().filter(i->i<elementosList.getSelectedIndex()).count()));
                this.correoField.setText(usuarioSeleccionado.getCorreo());
                this.tipoUsuarioField.setText(usuarioSeleccionado.getClass().getSimpleName());
                if (usuarioSeleccionado instanceof Cliente){
                    Cliente clienteSeleccionado = (Cliente) usuarioSeleccionado;
                    this.nombreField.setVisible(true);
                    this.nombreLabel.setVisible(true);
                    this.dniField.setVisible(true);
                    this.dniLabel.setVisible(true);
                    this.telefonoField.setVisible(true);
                    this.telefonoLabel.setVisible(true);
                    this.boolLabel.setVisible(true);
                    this.boolComboBox.setVisible(true);
                    this.extenderButton.setVisible(true);
                    this.nombreField.setText(clienteSeleccionado.getNombre());
                    this.dniField.setText(clienteSeleccionado.getDni());
                    this.telefonoField.setText(clienteSeleccionado.getTelefono());
                    if (usuarioSeleccionado instanceof Anfitrion){
                        Anfitrion anfitrionSeleccionado = (Anfitrion) usuarioSeleccionado;
                        this.boolLabel.setText("¿Es Súper Anfitrión?");
                        this.boolComboBox.setSelectedIndex(anfitrionSeleccionado.isSuperAnfitrion()?0:1);
                        this.fechaRegistroLabel.setVisible(true);
                        this.fechaRegistroField.setVisible(true);
                        this.fechaRegistroField.setText(anfitrionSeleccionado.getFechaRegistro().toString());
                        this.numeroTarjetaLabel.setVisible(false);
                        this.numeroTarjetaField.setVisible(false);
                        this.nombreTitularTarjetaLabel.setVisible(false);
                        this.nombreTitularTarjetaField.setVisible(false);
                        this.caducidadLabel.setVisible(false);
                        this.mesCaducidadLabel.setVisible(false);
                        this.mesSpinner.setVisible(false);
                        this.añoCaducidadLabel.setVisible(false);
                        this.añoSpinner.setVisible(false);
                        this.extenderButton.setText("Ver Inmuebles");
                    }else{
                        Particular particularSeleccionado = (Particular) usuarioSeleccionado;
                        this.boolLabel.setText("¿Es VIP?");
                        this.boolComboBox.setSelectedIndex(particularSeleccionado.isVip()?0:1);
                        this.fechaRegistroLabel.setVisible(false);
                        this.fechaRegistroField.setVisible(false);
                        this.numeroTarjetaLabel.setVisible(true);
                        this.numeroTarjetaField.setVisible(true);
                        this.nombreTitularTarjetaLabel.setVisible(true);
                        this.nombreTitularTarjetaField.setVisible(true);
                        this.caducidadLabel.setVisible(true);
                        this.mesCaducidadLabel.setVisible(true);
                        this.mesSpinner.setVisible(true);
                        this.añoCaducidadLabel.setVisible(true);
                        this.añoSpinner.setVisible(true);
                        this.numeroTarjetaField.setText(Long.toString(particularSeleccionado.getTarjeta().getNumero()));
                        this.nombreTitularTarjetaField.setText(particularSeleccionado.getTarjeta().getNombreTitular());
                        this.mesSpinner.setValue(particularSeleccionado.getTarjeta().getFechaCaducidad().getMonthValue());
                        this.añoSpinner.setValue(particularSeleccionado.getTarjeta().getFechaCaducidad().getYear());
                        this.extenderButton.setText("Ver Reservas");
                    }
                    indiceFijoBCB=this.boolComboBox.getSelectedIndex();
                }else{
                    this.nombreField.setVisible(false);
                    this.nombreLabel.setVisible(false);
                    this.dniField.setVisible(false);
                    this.dniLabel.setVisible(false);
                    this.telefonoField.setVisible(false);
                    this.telefonoLabel.setVisible(false);
                    this.boolLabel.setVisible(false);
                    this.boolComboBox.setVisible(false);
                    this.fechaRegistroLabel.setVisible(false);
                    this.fechaRegistroField.setVisible(false);
                    this.numeroTarjetaLabel.setVisible(false);
                    this.numeroTarjetaField.setVisible(false);
                    this.nombreTitularTarjetaLabel.setVisible(false);
                    this.nombreTitularTarjetaField.setVisible(false);
                    this.caducidadLabel.setVisible(false);
                    this.mesCaducidadLabel.setVisible(false);
                    this.mesSpinner.setVisible(false);
                    this.añoCaducidadLabel.setVisible(false);
                    this.añoSpinner.setVisible(false);
                    this.extenderButton.setVisible(false);
                }
                seleccionAnterior=elementosList.getSelectedIndex();
            }
            else if (posicionesSeparador.contains(elementosList.getSelectedIndex())){
                elementosList.setSelectedIndex(seleccionAnterior);
            }
        }
    }//GEN-LAST:event_elementosListValueChanged

    private void cerrarSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionButtonActionPerformed
        GUI_inicioSesion inicioSesion = new GUI_inicioSesion();
        inicioSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarSesionButtonActionPerformed

    private void añadirAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirAdminButtonActionPerformed
        GUI_dialogoAñadirAdmin dialogoAñadirAdmin = new GUI_dialogoAñadirAdmin(this, true);
        dialogoAñadirAdmin.setVisible(true);
        dialogoAñadirAdmin.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                refrescarLista();
            }
        });
    }//GEN-LAST:event_añadirAdminButtonActionPerformed

    private void borrarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarUsuarioButtonActionPerformed
        if (elementosList.getSelectedIndex()==-1 || posicionesSeparador.contains(elementosList.getSelectedIndex())){
            JOptionPane.showMessageDialog(this, "Selecciona un usuario para borrar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            boolean continuarBorradoPropio=false;
            LoginManager loginManager = new LoginManager();
            Usuario usuarioABorrar=ListManager.usuarios.get(elementosList.getSelectedIndex()-(int)posicionesSeparador.stream().filter(i->i<elementosList.getSelectedIndex()).count());
            boolean comenzarBorrado=JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres borrar a "+usuarioABorrar.getCorreo()+"?", "Borrar usuario", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION;
            if (!comenzarBorrado)
                return;
            if (usuarioABorrar instanceof Administrador){
                boolean continuarBorradoAdmin=JOptionPane.showConfirmDialog(this, "El usuario seleccionado es un administrador. ¿Seguro que quieres seguir?", "Borrar usuario", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE)==JOptionPane.YES_OPTION;
                if (!continuarBorradoAdmin)
                    return;
            }
            if (usuarioABorrar.equals(usuario)){
                continuarBorradoPropio=JOptionPane.showConfirmDialog(this, "El usuario seleccionado es el usuario actual. ¿Seguro que quieres seguir?\nSe cerrará la sesión", "Borrar usuario", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE)==JOptionPane.YES_OPTION;
                if (!continuarBorradoPropio)
                    return;
            }
            loginManager.borrarUsuario(usuarioABorrar.getCorreo());
            JOptionPane.showMessageDialog(this, "Usuario borrado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            refrescarLista();
            if (continuarBorradoPropio){
                cerrarSesionButtonActionPerformed(evt);
            }
        }
        catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_borrarUsuarioButtonActionPerformed

    private void boolComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boolComboBoxActionPerformed
        if (elementosList.getSelectedIndex()!=-1 && ListManager.usuarios.get(elementosList.getSelectedIndex()-(int)posicionesSeparador.stream().filter(i->i<elementosList.getSelectedIndex()).count()) instanceof Anfitrion){
            boolComboBox.setSelectedIndex(indiceFijoBCB);
        }
    }//GEN-LAST:event_boolComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_mainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_mainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_mainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_mainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_mainAdmin(null).setVisible(true);
            }
        });
    }
    
    public void initFrames(){
        this.calificacionField.setEditable(false);
        this.telefonoField.setEditable(false);
        this.datosArea.setEditable(false);
        this.direccionField.setEditable(false);
        this.dniField.setEditable(false);
        this.entradaField.setEditable(false);
        this.fechaRegistroField.setEditable(false);
        this.fechaReservaField.setEditable(false);
        this.fotoArea.setEditable(false);
        this.importeField.setEditable(false);
        this.correoField.setEditable(false);
        this.precioField.setEditable(false);
        this.salidaField.setEditable(false);
        this.serviciosArea.setEditable(false);
        this.tipoUsuarioField.setEditable(false);
        this.tipoInmuebleField.setEditable(false);
        this.tipoUsuarioField.setEditable(false);
        this.tituloField.setEditable(false);
        this.dniField.setEditable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirAdminButton;
    private javax.swing.JLabel añoCaducidadLabel;
    private javax.swing.JSpinner añoSpinner;
    private javax.swing.JComboBox<String> boolComboBox;
    private javax.swing.JLabel boolLabel;
    private javax.swing.JButton borrarUsuarioButton;
    private javax.swing.JLabel caducidadLabel;
    private javax.swing.JTextField calificacionField;
    private javax.swing.JButton cambiarContraseñaButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton cerrarSesionButton;
    private javax.swing.JTextField correoField;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JTextArea datosArea;
    private javax.swing.JTabbedPane datosPanel;
    private javax.swing.JTextField direccionField;
    private javax.swing.JTextField dniField;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JList<String> elementosList;
    private javax.swing.JTextField entradaField;
    private javax.swing.JButton extenderButton;
    private javax.swing.JTextField fechaRegistroField;
    private javax.swing.JLabel fechaRegistroLabel;
    private javax.swing.JTextField fechaReservaField;
    private javax.swing.JTextArea fotoArea;
    private javax.swing.JTextField importeField;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelDebug;
    private javax.swing.JComboBox<String> listaComboBox;
    private javax.swing.JLabel mesCaducidadLabel;
    private javax.swing.JSpinner mesSpinner;
    private javax.swing.JButton modificarButton;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTitularTarjetaField;
    private javax.swing.JLabel nombreTitularTarjetaLabel;
    private javax.swing.JTextField numeroTarjetaField;
    private javax.swing.JLabel numeroTarjetaLabel;
    private javax.swing.JTextField precioField;
    private javax.swing.JTextField salidaField;
    private javax.swing.JTextArea serviciosArea;
    private javax.swing.JTextField telefonoField;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JTextField tipoInmuebleField;
    private javax.swing.JTextField tipoUsuarioField;
    private javax.swing.JLabel tipoUsuarioLabel;
    private javax.swing.JTextField tituloField;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
